context:
  name: osv-scanner 
  version: "2.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/google/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: c419edd454980d7a8c7401baed04748d40342d6a77c1317696876986f171664b
    target_directory: src

build:
  number: 0
  script:
    - cd src
    # github.com/mattn/go-localereader is an unknown license but is MIT-licensed
    - go-licenses save ./cmd/osv-scanner --save_path ../library_licenses --ignore github.com/google/osv-scanner --ignore github.com/mattn/go-localereader
    - if: win
      then: go build -v -trimpath -o %LIBRARY_BIN%\osv-scanner.exe -ldflags="-s" ./cmd/osv-scanner
      else: go build -v -trimpath -o $PREFIX/bin/osv-scanner -ldflags="-s -w" ./cmd/osv-scanner


requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - osv-scanner --help

about:
  homepage: https://github.com/google/osv-scanner
  summary: Vulnerability scanner written in Go which uses the data provided by https://osv.dev
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  repository: https://github.com/google/osv-scanner

extra:
  recipe-maintainers:
    - delsner
