context:
  name: osv-scanner
  version: "2.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/google/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 129f534cb55c0811dcf80efec9da7314a4fd87255c093718db9502a4ba19f704
    target_directory: src

build:
  number: 0
  script:
    - cd src
    # github.com/mattn/go-localereader is an unknown license but is MIT-licensed
    # modernc.org/mathutil is a BSD-3-Clause license, but the license file is not present in the source code
    - go-licenses save ./cmd/osv-scanner --save_path ../library_licenses --ignore github.com/google/osv-scanner --ignore github.com/mattn/go-localereader --ignore modernc.org/mathutil
    - if: win
      then: go build -v -trimpath -o %LIBRARY_BIN%\osv-scanner.exe -ldflags="-s" ./cmd/osv-scanner
      else: go build -v -trimpath -o $PREFIX/bin/osv-scanner -ldflags="-s -w" ./cmd/osv-scanner


requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - osv-scanner --help

about:
  homepage: https://github.com/google/osv-scanner
  summary: Vulnerability scanner written in Go which uses the data provided by https://osv.dev
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  repository: https://github.com/google/osv-scanner

extra:
  recipe-maintainers:
    - delsner
